apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-policy
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
    - name: br1-multus
      description: Linux bridge linked to bond1
      type: linux-bridge
      state: up
      ipv4:
        dhcp: false
        enabled: false
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: bond1
